name: Integration Tests on Web

on:
  # Uncomment to enable manual trigger
  # workflow_dispatch:
  push:
    branches: [ main, master ]
    paths:
      - 'lib/**'
      - 'web/**'
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [ main, master ]
    paths:
      - 'lib/**'
      - 'web/**'

jobs:
  web_integration_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'
          channel: 'stable'

      - name: Install Flutter dependencies
        run: |
          flutter pub get
          cd example
          flutter pub get

      - name: Enable web support
        run: flutter config --enable-web

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install Python and webdriver-manager
        run: |
          sudo apt-get install -y python3 python3-pip
          pip3 install webdriver-manager

      - name: Setup ChromeDriver with webdriver-manager
        run: |
          # Use webdriver-manager to download the compatible ChromeDriver
          CHROMEDRIVER_PATH=$(python3 -c "from webdriver_manager.chrome import ChromeDriverManager; print(ChromeDriverManager().install())")
          echo "ChromeDriver installed at: $CHROMEDRIVER_PATH"

          # Start ChromeDriver
          $CHROMEDRIVER_PATH --port=4444 &
          sleep 3  # Give ChromeDriver time to start

      - name: Run integration tests on Web
        run: |
          cd example
          flutter drive \
            --driver=test_driver/integration_test.dart \
            --target=integration_test/all_tests.dart \
            -d web-server \
            --web-port=8080 \
            --browser-name=chrome