name: ONNX Runtime Integration Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  linux_integration_test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'
          channel: 'stable'

      - name: Enable Linux desktop support
        run: flutter config --enable-linux-desktop

      - name: Install dependencies
        run: |
          flutter pub get
          cd example
          flutter pub get

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          # Install basic build dependencies
          sudo apt-get install -y libgtk-3-dev libx11-dev pkg-config cmake ninja-build libblkid-dev xvfb
          # Install OpenGL dependencies
          sudo apt-get install -y libegl1 libgl1 libxcb-xinerama0 libglu1-mesa libgl1-mesa-dri
          # Check installed GL/EGL libraries
          ls -la /usr/lib/x86_64-linux-gnu/libEGL* || echo "No EGL libs found in expected location"
          ls -la /usr/lib/x86_64-linux-gnu/libGL* || echo "No GL libs found in expected location"

      - name: Verify model file exists
        run: |
          find . -name "addition_model.ort" || echo "Model not found!"
          ls -la example/assets/models || echo "Directory not found!"

      - name: Run integration tests on Linux with Xvfb
        run: |
          # Create a simple wrapper app in the example directory
          cd example
          
          # Create a minimal flutter app with a main.dart that invokes the integration test
          mkdir -p test_app
          cd test_app
          
          # Initialize Flutter project
          flutter create --platforms=linux .
          
          # Copy the integration test to this project
          mkdir -p integration_test
          cp ../integration_test/onnxruntime_integration_test.dart integration_test/
          
          # Copy the model to the assets directory
          mkdir -p assets/models
          cp ../assets/models/addition_model.ort assets/models/
          
          # Update pubspec.yaml to include the assets and dependencies
          cat > pubspec.yaml << 'EOL'
          name: onnxruntime_test_app
          description: Test app for ONNX Runtime integration tests
          publish_to: 'none'
          version: 1.0.0+1
          
          environment:
            sdk: '>=3.0.0 <4.0.0'
          
          dependencies:
            flutter:
              sdk: flutter
            flutter_onnxruntime:
              path: ../..
            integration_test:
              sdk: flutter
            flutter_test:
              sdk: flutter
              
          flutter:
            assets:
              - assets/models/
          EOL
          
          # Update dependencies
          flutter pub get
          
          # Use xvfb-run to run the integration test
          xvfb-run --auto-servernum flutter test integration_test/onnxruntime_integration_test.dart -d linux --no-sound-null-safety

  macos_integration_test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'
          channel: 'stable'

      - name: Enable macOS desktop support
        run: flutter config --enable-macos-desktop

      - name: Install dependencies
        run: |
          flutter pub get
          cd example
          flutter pub get

      - name: Verify model file exists
        run: |
          find . -name "addition_model.ort" || echo "Model not found!"
          ls -la example/assets/models || echo "Directory not found!"

      - name: Run integration tests on macOS
        run: |
          # Use the existing example app
          cd example
          
          # Run the integration test directly
          flutter test integration_test/onnxruntime_integration_test.dart -d macos 