name: ONNX Runtime Integration Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  linux_integration_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'
          channel: 'stable'

      - name: Enable Linux desktop support
        run: flutter config --enable-linux-desktop

      - name: Install dependencies
        run: |
          flutter pub get
          cd example
          flutter pub get

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libx11-dev pkg-config cmake ninja-build libblkid-dev xvfb
          # Required for OpenGL support in headless environments
          sudo apt-get install -y libegl1-mesa libgl1-mesa-dri libxcb-xinerama0

      - name: Verify model file exists
        run: |
          find . -name "addition_model.ort" || echo "Model not found!"
          ls -la example/assets/models || echo "Directory not found!"

      - name: Run integration tests on Linux with Xvfb
        run: |
          # Build the app first to ensure the plugin is properly compiled
          cd example
          flutter build linux --debug

          # Use xvfb-run to provide a virtual display
          xvfb-run --auto-servernum flutter test integration_test/onnxruntime_integration_test.dart -d linux --verbose

  macos_integration_test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'
          channel: 'stable'

      - name: Enable macOS desktop support
        run: flutter config --enable-macos-desktop

      - name: Install dependencies
        run: |
          flutter pub get
          cd example
          flutter pub get

      - name: Verify model file exists
        run: |
          find . -name "addition_model.ort" || echo "Model not found!"
          ls -la example/assets/models || echo "Directory not found!"

      - name: Run integration tests on macOS
        run: |
          # Build the app first to ensure the plugin is properly compiled
          cd example
          flutter build macos --debug
          # Run the integration tests directly from the example app
          flutter test integration_test/onnxruntime_integration_test.dart -d macos 