name: ONNX Runtime Integration Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  linux_integration_test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'
          channel: 'stable'
          
      - name: Install dependencies
        run: |
          cd example
          flutter pub get
        
      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libx11-dev pkg-config cmake ninja-build libblkid-dev
      
      - name: Enable Linux desktop support
        run: flutter config --enable-linux-desktop
      
      - name: Run integration tests on Linux
        run: |
          cd example
          flutter test integration_test/onnxruntime_integration_test.dart -d linux
          
  macos_integration_test:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'
          channel: 'stable'
          
      - name: Install dependencies
        run: |
          cd example
          flutter pub get
      
      - name: Enable macOS desktop support
        run: flutter config --enable-macos-desktop
      
      - name: Run integration tests on macOS
        run: |
          cd example
          flutter test integration_test/onnxruntime_integration_test.dart -d macos 