name: ONNX Runtime Integration Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  macos_integration_test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'
          channel: 'stable'

      - name: Enable macOS desktop support
        run: flutter config --enable-macos-desktop

      - name: Install dependencies
        run: |
          flutter pub get
          cd example
          flutter pub get

      - name: Verify model file exists
        run: |
          find . -name "addition_model.ort" || echo "Model not found!"
          ls -la example/assets/models || echo "Directory not found!"

      - name: Run integration tests on macOS
        run: |
          # Use the existing example app
          cd example
          
          # Run the integration test directly
          flutter test integration_test/onnxruntime_integration_test.dart -d macos 

  android_integration_test:
    runs-on: macos-13 # macOS runner needed for Android emulator

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'
          channel: 'stable'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Install dependencies
        run: |
          flutter pub get
          cd example
          flutter pub get

      - name: Verify model file exists
        run: |
          find . -name "addition_model.ort" || echo "Model not found!"
          ls -la example/assets/models || echo "Directory not found!"

      - name: Start Android emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 26
          arch: x86_64
          target: google_apis
          profile: Nexus 6
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          script: |
            # Use the existing example app
            cd example
            
            # Run the integration test on the Android emulator
            flutter test integration_test/onnxruntime_integration_test.dart -d android 